name: Release distribution to production

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          repository: PNW-Individual-Couple-Therapy/marketing-site-staging
          path: staging
          token: ${{ secrets.DEPLOY_PRODUCTION }}
      - uses: actions/checkout@v3
        with:
          repository: PNW-Individual-Couple-Therapy/marketing-site-production
          path: production
          token: ${{ secrets.DEPLOY_PRODUCTION }}

      - name: Copy distribution into -production
        run: |
          ls -la production
          rm -rf production/docs
          ls -la production
          mkdir production/docs
          ls -la production
          cp -R staging/docs/* production/docs
          ls -la production
        
      - name: Create pull request
        run: |
          cd production
          ls -la

